### ISSUE TITLE
next js production build error

### ISSUE THREAD

**Issue by zilkenberg22** [JiHong88/SunEditor#1073]
To make it easier for us to help you, please include as much useful information as possible.

## Version
"suneditor": "^2.43.14",
"suneditor-react": "^3.4.1"

## Error msg
```
info  - Collecting page data ../data/editor/node_modules/suneditor/src/plugins/index.js:4
import blockquote from './command/blockquote';

---
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
---
```

## Main code
```
import React from "react";
import dynamic from "next/dynamic";
import "suneditor/dist/css/suneditor.min.css"; // Import Sun Editor's CSS File
import plugins from "suneditor/src/plugins";

const SunEditor = dynamic(() => import("suneditor-react"), {
    ssr: false,
});

export default function Index(props) {

    var custom_container = {
        name: "custom_container",
        display: "container",
        add: function (core, targetElement) {
            const context = core.context;
            context.custom_container = {};
            let listDiv = this.setSubmenu(core);
            listDiv.querySelector(".se-form-group").addEventListener("click", this.onClick.bind(core));
            core.initMenuTarget(this.name, targetElement, listDiv);
        },
        setSubmenu: function (core) {
            const listDiv = core.util.createElement("DIV");
            const icons = core.icons;
            listDiv.className = "se-menu-container se-submenu se-list-layer";
            listDiv.innerHTML =
                "" +
                '<div class="se-list-inner">' +
                '<div class="se-form-group">' +
                "<div>" +
                '<button type="button" class="se-btn se-tooltip" data-command="bold" style="margin: 0 !important;">' +
                icons.bold +
                '<span class="se-tooltip-inner">' +
                '<span class="se-tooltip-text">Quote</span>' +
                "</span>" +
                "</button>" +
                "</div>" +
                "<div>" +
                '<button type="button" class="se-btn se-tooltip" data-command="blockquote">' +
                icons.blockquote +
                '<span class="se-tooltip-inner">' +
                '<span class="se-tooltip-text">Quote</span>' +
                "</span>" +
                "</button>" +
                "</div>" +
                "<div>" +
                '<button type="button" class="se-btn se-tooltip" data-command="link">' +
                icons.link +
                '<span class="se-tooltip-inner">' +
                '<span class="se-tooltip-text">Link</span>' +
                "</span>" +
                "</button>" +
                "</div>" +
                "<div>" +
                '<button type="button" class="se-btn se-tooltip" data-command="table">' +
                icons.table +
                '<span class="se-tooltip-inner">' +
                '<span class="se-tooltip-text">Table</span>' +
                "</span>" +
                "</button>" +
                "</div>" +
                "<div>" +
                '<button type="button" class="se-btn se-tooltip" data-command="textStyle">' +
                icons.text_style +
                '<span class="se-tooltip-inner">' +
                '<span class="se-tooltip-text">Text style</span>' +
                "</span>" +
                "</button>" +
                "</div>" +
                "</div>" +
                "</div>";

            return listDiv;
        },
        onClick: function (e) {
            e.preventDefault();
            e.stopPropagation();

            let target = e.target;
            let command = "";

            while (!command && !/^UL$/i.test(target.tagName)) {
                command = target.getAttribute("data-command");
                if (command) break;
                target = target.parentNode;
            }

            if (!command) return;

            const plugin = this.plugins[command];
            this.actionCall(command, plugin ? plugin.display : "", target);
        },
    };
    return (
        <div>
            <p> My Other Contents </p>
            <SunEditor
                setOptions={{
                    height: 200,
                    plugins: { ...{ custom_container }, ...plugins },
                    buttonList: [
                        ["formatBlock", "font", "fontSize", "fontColor", "align", "paragraphStyle", "blockquote"],
                        ["bold", "underline", "italic", "strike", "subscript", "superscript"],
                        ["removeFormat"],
                        ["outdent", "indent"],
                        ["table", "list"],
                        ["link", "image", "video"],
                        [
                            {
                                name: "custom_container",
                                dataDisplay: "container",
                                title: "custom_container",
                                buttonClass: "",
                                innerHTML:
                                    '<svg viewBox="0 0 24 24" style="width:24px;height:24px;"><path fill="currentColor" d="M6 10c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm12 0c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm-6 0c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z" /></svg>',
                            },
                        ],
                    ],
                }}
            />
        </div>
    );
}

```

**Comment by zilkenberg22** [comment]
## this code build working
```
 <SunEditor
                setOptions={{
                    height: 200,
                    buttonList: [
                        ["formatBlock", "font", "fontSize", "fontColor", "align", "paragraphStyle", "blockquote"],
                        ["bold", "underline", "italic", "strike", "subscript", "superscript"],
                        ["removeFormat"],
                        ["outdent", "indent"],
                        ["table", "list"],
                        ["link", "image", "video"],
                    ],
                }}
            />
```

## this code not working
 ```
<SunEditor
                setOptions={{
                    height: 200,
                    plugins: { ...plugins }, // or {...{custom_plugin}, ...plugins}
                    buttonList: [
                        ["formatBlock", "font", "fontSize", "fontColor", "align", "paragraphStyle", "blockquote"],
                        ["bold", "underline", "italic", "strike", "subscript", "superscript"],
                        ["removeFormat"],
                        ["outdent", "indent"],
                        ["table", "list"],
                        ["link", "image", "video"],
                    ],
                }}
            />
```

**Comment by zilkenberg22** [comment]
if i called plugins not working my code

**Comment by zilkenberg22** [comment]
@JiHong88 Please help me

**Comment by iorphx** [comment]
Try import plugins as dynamic import

```
import plugins from 'suneditor/src/plugins';
```
Change above code into below using dynamic import.

```
const plugins = dynamic(() => import('suneditor/src/plugins'), { ssr: false });
```

**Comment by JiHong88** [comment]
@zilkenberg22 What error message are you getting?

**Comment by zilkenberg22** [comment]
> @zilkenberg22 What error message are you getting?

info  - Collecting page data ../data/editor/node_modules/suneditor/src/plugins/index.js:4
import blockquote from './command/blockquote';

---
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
---

**Comment by zilkenberg22** [comment]
> @zilkenberg22 What error message are you getting?

info  - Collecting page data ../data/editor/node_modules/suneditor/src/plugins/index.js:4
import blockquote from './command/blockquote';

---
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
---

**Comment by JiHong88** [comment]
This appears to be an "import" syntax problem.
Sorry, I can't test "reactjs" right now. :(
Take a look at this link. https://github.com/JiHong88/SunEditor/issues/1037

**Comment by JiHong88** [comment]
@zilkenberg22 Custom plugins must be registered as follows:
`plugins: {custom_plugin, ...plugins}`
