### ISSUE TITLE
Object.setContents miserably fails ;-(

### ISSUE THREAD

**Issue by PierreKauffmann** [JiHong88/suneditor#1118]
**Using** 
```
"suneditor": "2.44.3",
"suneditor-react": "3.4.1",
```

**Error** 
```
TypeError: Cannot read properties of null (reading 'replaceChild')
    at Object.update_image (image.js:793:45)
    at Object.<anonymous> (image.js:629:38)
    at Object.checkInfo (fileManager.js:141:21)
    at Object.checkFileInfo (image.js:633:44)
    at Object._checkComponents (core.js:5730:44)
    at f (history.js:55:14)
    at Object.push (history.js:114:21)
    at Object.setContents (core.js:5057:30)
    at Object.setContents (core.js:8721:18)
    at Ue (EditMessageItem.js:537:10)
```

**Our code is EditMessageItem.js**
`editor.setContents(newContent);`

**`newContent` is an HTML TEXT** 
```
<a
  download="README"
  href="https://github.com/JiHong88/SunEditor/blob/master/README.md"
  target="_blank"
>
  <img
    src="https://google.com"
    alt="icon1"
  />
  <img
    src="https://google.com"
    alt="icon2"
  />
</a>
```

It works with 1 image in the `<a ...>` tag !!! 

Should be easy and super fast to fix ;-)

**Comment by PierreKauffmann** [comment]
THX @JiHong88  to put this in the next milestone ;-)

**Comment by PierreKauffmann** [comment]
Is there a target date for the 2.44.4 milestone?

**Comment by JiHong88** [comment]
Sorry, I had a lot of busy work.
Updated milestone dates.

https://github.com/JiHong88/SunEditor/milestone/51

**Comment by PierreKauffmann** [comment]
THX for all the hard work, looking forward to see it ;-)

**Comment by JiHong88** [comment]
The [2.44.4](https://github.com/JiHong88/suneditor/releases/tag/2.44.4) version has been updated.
Thank you.
