### ISSUE TITLE
Adding image sometimes throws error

### ISSUE THREAD

**Issue by numanbaig** [JiHong88/SunEditor#1366]
adding image sometimes throws error
Error: 
Uncaught TypeError: Cannot read properties of null (reading 'previousElementSibling')
    at Object.removeNode (core.js:2146:45)
    at Object.insertComponent (core.js:1565:28)
    at Object.create_image (image.js:677:18)
    at Object.onRender_imgBase64 (image.js:556:30)
    at Object.<anonymous> (image.js:533:63)
    
**To Reproduce**
add multiple images

**Expected behavior**
should add images without error

**Screenshots**
![image](https://github.com/JiHong88/suneditor/assets/43302314/ca9b77b6-2099-40e9-bd49-5fddf9317eba)

**Comment by inday-jin** [comment]
editor getRange_addLine function add

editor.core.getRange_addLine(editor.core.getRange());
await uploadHandler(response);

**Comment by Lokheim** [comment]
> editor getRange_addLine function add
> 
> editor.core.getRange_addLine(editor.core.getRange()); await uploadHandler(response);

Where to put this code when i use react-suneditor ?
