### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by sosalejandro** [JiHong88/SunEditor#770]
I'm facing this error like this guy had in the past.
#178 

I've tried changing my target, module and package.json module as StackOverflow suggested in this issue but I haven't been able to fix it. I tried changing the import to require but no success. It's the first time I'm using this editor and the problem comes from the core as I'm using the React component. 
TypeScript project.

error output
```
C:\Users\myuser\source\repos\RichTextEditor\client\node_modules\suneditor\src\suneditor.js:10
import core from './lib/core';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1024:16)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\Users\Wata-\source\repos\RichTextEditor\client\node_modules\suneditor-react\dist\SunEditor.js:21:35)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\Users\Wata-\source\repos\RichTextEditor\client\node_modules\suneditor-react\dist\index.js:26:35)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```
package.json
```{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "10.2.3",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "suneditor": "^2.39.0",
    "suneditor-react": "^3.1.1"
  },
  "devDependencies": {
    "@types/react": "17.0.8",
    "typescript": "4.3.2"
  }
}
```

**Comment by JiHong88** [comment]
I think, it does not appear to be a setting problem of the editor itself.
Hope this link is helpful. https://github.com/babel/babel/discussions/12463
