### ISSUE TITLE
This error still persist  - Uncaught TypeError: this._iframeAutoHeight is not a function at Object._resourcesStateChange (core.js:5548:18)

### ISSUE THREAD

**Issue by roker15** [JiHong88/SunEditor#940]
To make it easier for us to help you, please include as much useful information as possible.

## Version
Write the version of the Editor you are currently using.

**Comment by JiHong88** [comment]
https://github.com/mkhstar/suneditor-react/issues/252
Is this issue unresolved?

**Comment by roker15** [comment]
> [mkhstar/suneditor-react#252](https://github.com/mkhstar/suneditor-react/issues/252) Is this issue unresolved?

Yes it does. There should be something to catch any error by suneditor in react.

**Comment by JiHong88** [comment]
https://github.com/mkhstar/suneditor-react/issues/252
This issue is not reproduced at the current version..

Version 3 is still under development.
In the meantime, I was not able to proceed due to a lot of work.
I aim to release it before summer.

**Comment by roker15** [comment]
> [mkhstar/suneditor-react#252](https://github.com/mkhstar/suneditor-react/issues/252) This issue is not reproduced at the current version..
> 
> Version 3 is still under development. In the meantime, I was not able to proceed due to a lot of work. I aim to release it before summer.

I am using next js, already summer in india.

**Comment by JiHong88** [comment]
Sorry, I don't know well the "nextjs" :(
It seems to be a "nextjs" environment issue.

**Comment by JiHong88** [comment]
https://github.com/mkhstar/suneditor-react/issues/252
This issue is not reproduced.😔

>This error still persist - Uncaught TypeError: this._iframeAutoHeight is not a function at Object._resourcesStateChange (core.js:5548:18) #940

This error maybe occured error on the "next's".
